name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Get the code
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3

      - name: Install dependencies
        run: make devenv

      - name: Test
        run: make test

      - uses: getsentry/action-gocd-jsonnet@v1
        with:
          jb-install: true
          check-for-changes: false
          jsonnet-dir: .
          generated-dir: ./generated-pipelines
          render-jsonnet-files: false
